In [1]:
import pandas as pd
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules

In [2]:
dataset = [['Milk', 'Onion', 'Nutmeg', 'Kidney Beans', 'Eggs', 'Yogurt'],
           ['Dill', 'Onion', 'Nutmeg', 'Kidney Beans', 'Eggs', 'Yogurt'],
           ['Milk', 'Apple', 'Kidney Beans', 'Eggs'],
           ['Milk', 'Unicorn', 'Corn', 'Kidney Beans', 'Yogurt'],
           ['Corn', 'Onion', 'Onion', 'Kidney Beans', 'Ice cream', 'Eggs']]

In [3]:
te = TransactionEncoder()
te_ary = te.fit(dataset).transform(dataset)

In [4]:
df = pd.DataFrame(te_ary, columns=te.columns_)
df.head()

,Apple,Corn,Dill,Eggs,Ice cream,Kidney Beans,Milk,Nutmeg,Onion,Unicorn,Yogurt
0,False,False,False,True,False,True,True,True,True,False,True
1,False,False,True,True,False,True,False,True,True,False,True
2,True,False,False,True,False,True,True,False,False,False,False
3,False,True,False,False,False,True,True,False,False,True,True
4,False,True,False,True,True,True,False,False,True,False,False

In [5]:
frequent_itemsets = apriori(df, min_support = 0.001, use_colnames=True)
frequent_itemsets.head()

   support     itemsets
0      0.2      (Apple)
1      0.4       (Corn)
2      0.2       (Dill)
3      0.8       (Eggs)
4      0.2  (Ice cream)

In [6]:
rules = association_rules(frequent_itemsets, metric="confidence", min_threshold = 0.001)

In [7]:
rules.head()

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,(Eggs),(Apple),0.8,0.2,0.2,0.25,1.250000,0.04,1.066667
1,(Apple),(Eggs),0.2,0.8,0.2,1.00,1.250000,0.04,inf
2,(Kidney Beans),(Apple),1.0,0.2,0.2,0.20,1.000000,0.00,1.000000
3,(Apple),(Kidney Beans),0.2,1.0,0.2,1.00,1.000000,0.00,inf
4,(Apple),(Milk),0.2,0.6,0.2,1.00,1.666667,0.08,inf

In [8]:
type(rules)

pandas.core.frame.DataFrame

In [10]:
rules.iloc[0:2,:]

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,(Apple),(Eggs),0.2,0.8,0.2,1.00,1.25,0.04,inf
1,(Eggs),(Apple),0.8,0.2,0.2,0.25,1.25,0.04,1.066667

In [11]:
rules.loc[rules['antecedents'] == rules.iloc[0,0], ]

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,(Apple),(Eggs),0.2,0.8,0.2,1.0,1.250000,0.04,inf
2,(Apple),(Kidney Beans),0.2,1.0,0.2,1.0,1.000000,0.00,inf
4,(Apple),(Milk),0.2,0.6,0.2,1.0,1.666667,0.08,inf
75,(Apple),"(Eggs, Kidney Beans)",0.2,0.8,0.2,1.0,1.250000,0.04,inf
81,(Apple),"(Eggs, Milk)",0.2,0.4,0.2,1.0,2.500000,0.12,inf
87,(Apple),"(Kidney Beans, Milk)",0.2,0.6,0.2,1.0,1.666667,0.08,inf
388,(Apple),"(Eggs, Kidney Beans, Milk)",0.2,0.4,0.2,1.0,2.500000,0.12,inf

In [12]:
rules.iloc[0,0]

frozenset({'Apple'})

In [13]:
rules.iloc[:,0].unique()

array([frozenset({'Apple'}), frozenset({'Eggs'}),
       frozenset({'Kidney Beans'}), frozenset({'Milk'}),
       frozenset({'Corn'}), frozenset({'Ice cream'}),
       frozenset({'Onion'}), frozenset({'Unicorn'}),
       frozenset({'Yogurt'}), frozenset({'Dill'}), frozenset({'Nutmeg'}),
       frozenset({'Apple', 'Eggs'}), frozenset({'Apple', 'Kidney Beans'}),
       frozenset({'Eggs', 'Kidney Beans'}), frozenset({'Apple', 'Milk'}),
       frozenset({'Eggs', 'Milk'}), frozenset({'Kidney Beans', 'Milk'}),
       frozenset({'Ice cream', 'Corn'}), frozenset({'Ice cream', 'Eggs'}),
       frozenset({'Corn', 'Eggs'}), frozenset({'Corn', 'Kidney Beans'}),
       frozenset({'Onion', 'Corn'}), frozenset({'Onion', 'Eggs'}),
       frozenset({'Ice cream', 'Kidney Beans'}),
       frozenset({'Onion', 'Ice cream'}), frozenset({'Corn', 'Milk'}),
       frozenset({'Onion', 'Kidney Beans'}),
       frozenset({'Unicorn', 'Corn'}),
       frozenset({'Unicorn', 'Kidney Beans'}),
       frozenset({'Corn', 'Yogurt'}),
       frozenset({'Yogurt', 'Kidney Beans'}),
       frozenset({'Unicorn', 'Milk'}), frozenset({'Yogurt', 'Milk'}),
       frozenset({'Unicorn', 'Yogurt'}), frozenset({'Dill', 'Eggs'}),
       frozenset({'Dill', 'Kidney Beans'}), frozenset({'Dill', 'Nutmeg'}),
       frozenset({'Eggs', 'Nutmeg'}), frozenset({'Onion', 'Dill'}),
       frozenset({'Dill', 'Yogurt'}), frozenset({'Eggs', 'Yogurt'}),
       frozenset({'Nutmeg', 'Kidney Beans'}),
       frozenset({'Onion', 'Nutmeg'}), frozenset({'Nutmeg', 'Yogurt'}),
       frozenset({'Onion', 'Yogurt'}), frozenset({'Nutmeg', 'Milk'}),
       frozenset({'Onion', 'Milk'}),
       frozenset({'Apple', 'Eggs', 'Kidney Beans'}),
       frozenset({'Apple', 'Eggs', 'Milk'}),
       frozenset({'Apple', 'Kidney Beans', 'Milk'}),
       frozenset({'Eggs', 'Kidney Beans', 'Milk'}),
       frozenset({'Ice cream', 'Corn', 'Eggs'}),
       frozenset({'Ice cream', 'Corn', 'Kidney Beans'}),
       frozenset({'Ice cream', 'Eggs', 'Kidney Beans'}),
       frozenset({'Corn', 'Eggs', 'Kidney Beans'}),
       frozenset({'Onion', 'Ice cream', 'Corn'}),
       frozenset({'Onion', 'Ice cream', 'Eggs'}),
       frozenset({'Onion', 'Corn', 'Eggs'}),
       frozenset({'Onion', 'Corn', 'Kidney Beans'}),
       frozenset({'Onion', 'Eggs', 'Kidney Beans'}),
       frozenset({'Onion', 'Ice cream', 'Kidney Beans'}),
       frozenset({'Unicorn', 'Corn', 'Kidney Beans'}),
       frozenset({'Unicorn', 'Corn', 'Milk'}),
       frozenset({'Unicorn', 'Kidney Beans', 'Milk'}),
       frozenset({'Corn', 'Kidney Beans', 'Milk'}),
       frozenset({'Yogurt', 'Corn', 'Kidney Beans'}),
       frozenset({'Corn', 'Yogurt', 'Milk'}),
       frozenset({'Yogurt', 'Kidney Beans', 'Milk'}),
       frozenset({'Unicorn', 'Corn', 'Yogurt'}),
       frozenset({'Unicorn', 'Yogurt', 'Kidney Beans'}),
       frozenset({'Unicorn', 'Yogurt', 'Milk'}),
       frozenset({'Dill', 'Eggs', 'Kidney Beans'}),
       frozenset({'Dill', 'Eggs', 'Nutmeg'}),
       frozenset({'Dill', 'Kidney Beans', 'Nutmeg'}),
       frozenset({'Nutmeg', 'Eggs', 'Kidney Beans'}),
       frozenset({'Onion', 'Dill', 'Eggs'}),
       frozenset({'Onion', 'Dill', 'Kidney Beans'}),
       frozenset({'Dill', 'Yogurt', 'Kidney Beans'}),
       frozenset({'Dill', 'Eggs', 'Yogurt'}),
       frozenset({'Yogurt', 'Eggs', 'Kidney Beans'}),
       frozenset({'Onion', 'Dill', 'Nutmeg'}),
       frozenset({'Onion', 'Eggs', 'Nutmeg'}),
       frozenset({'Dill', 'Yogurt', 'Nutmeg'}),
       frozenset({'Nutmeg', 'Eggs', 'Yogurt'}),
       frozenset({'Onion', 'Dill', 'Yogurt'}),
       frozenset({'Onion', 'Eggs', 'Yogurt'}),
       frozenset({'Onion', 'Nutmeg', 'Kidney Beans'}),
       frozenset({'Yogurt', 'Kidney Beans', 'Nutmeg'}),
       frozenset({'Onion', 'Yogurt', 'Kidney Beans'}),
       frozenset({'Onion', 'Nutmeg', 'Yogurt'}),
       frozenset({'Eggs', 'Nutmeg', 'Milk'}),
       frozenset({'Kidney Beans', 'Nutmeg', 'Milk'}),
       frozenset({'Onion', 'Eggs', 'Milk'}),
       frozenset({'Onion', 'Kidney Beans', 'Milk'}),
       frozenset({'Eggs', 'Yogurt', 'Milk'}),
       frozenset({'Onion', 'Nutmeg', 'Milk'}),
       frozenset({'Yogurt', 'Nutmeg', 'Milk'}),
       frozenset({'Onion', 'Yogurt', 'Milk'}),
       frozenset({'Onion', 'Ice cream', 'Corn', 'Eggs'}),
       frozenset({'Onion', 'Corn', 'Eggs', 'Kidney Beans'}),
       frozenset({'Ice cream', 'Corn', 'Eggs', 'Kidney Beans'}),
       frozenset({'Onion', 'Ice cream', 'Corn', 'Kidney Beans'}),
       frozenset({'Onion', 'Ice cream', 'Eggs', 'Kidney Beans'}),
       frozenset({'Unicorn', 'Corn', 'Kidney Beans', 'Yogurt'}),
       frozenset({'Unicorn', 'Corn', 'Yogurt', 'Milk'}),
       frozenset({'Unicorn', 'Corn', 'Kidney Beans', 'Milk'}),
       frozenset({'Unicorn', 'Kidney Beans', 'Yogurt', 'Milk'}),
       frozenset({'Corn', 'Kidney Beans', 'Yogurt', 'Milk'}),
       frozenset({'Onion', 'Dill', 'Eggs', 'Nutmeg'}),
       frozenset({'Onion', 'Kidney Beans', 'Eggs', 'Nutmeg'}),
       frozenset({'Dill', 'Kidney Beans', 'Eggs', 'Nutmeg'}),
       frozenset({'Onion', 'Dill', 'Eggs', 'Kidney Beans'}),
       frozenset({'Onion', 'Dill', 'Kidney Beans', 'Nutmeg'}),
       frozenset({'Dill', 'Yogurt', 'Eggs', 'Nutmeg'}),
       frozenset({'Yogurt', 'Kidney Beans', 'Eggs', 'Nutmeg'}),
       frozenset({'Dill', 'Kidney Beans', 'Eggs', 'Yogurt'}),
       frozenset({'Dill', 'Kidney Beans', 'Yogurt', 'Nutmeg'}),
       frozenset({'Onion', 'Dill', 'Eggs', 'Yogurt'}),
       frozenset({'Onion', 'Kidney Beans', 'Eggs', 'Yogurt'}),
       frozenset({'Onion', 'Dill', 'Kidney Beans', 'Yogurt'}),
       frozenset({'Onion', 'Nutmeg', 'Eggs', 'Yogurt'}),
       frozenset({'Onion', 'Dill', 'Yogurt', 'Nutmeg'}),
       frozenset({'Onion', 'Yogurt', 'Kidney Beans', 'Nutmeg'}),
       frozenset({'Onion', 'Eggs', 'Kidney Beans', 'Milk'}),
       frozenset({'Onion', 'Eggs', 'Nutmeg', 'Milk'}),
       frozenset({'Nutmeg', 'Eggs', 'Kidney Beans', 'Milk'}),
       frozenset({'Onion', 'Nutmeg', 'Kidney Beans', 'Milk'}),
       frozenset({'Yogurt', 'Eggs', 'Kidney Beans', 'Milk'}),
       frozenset({'Nutmeg', 'Eggs', 'Yogurt', 'Milk'}),
       frozenset({'Yogurt', 'Milk', 'Kidney Beans', 'Nutmeg'}),
       frozenset({'Onion', 'Eggs', 'Yogurt', 'Milk'}),
       frozenset({'Onion', 'Kidney Beans', 'Yogurt', 'Milk'}),
       frozenset({'Onion', 'Nutmeg', 'Yogurt', 'Milk'}),
       frozenset({'Eggs', 'Onion', 'Dill', 'Yogurt', 'Nutmeg'}),
       frozenset({'Eggs', 'Nutmeg', 'Onion', 'Dill', 'Kidney Beans'}),
       frozenset({'Eggs', 'Nutmeg', 'Onion', 'Yogurt', 'Kidney Beans'}),
       frozenset({'Eggs', 'Dill', 'Kidney Beans', 'Yogurt', 'Nutmeg'}),
       frozenset({'Eggs', 'Onion', 'Dill', 'Yogurt', 'Kidney Beans'}),
       frozenset({'Nutmeg', 'Onion', 'Dill', 'Yogurt', 'Kidney Beans'}),
       frozenset({'Eggs', 'Onion', 'Yogurt', 'Kidney Beans', 'Milk'}),
       frozenset({'Eggs', 'Onion', 'Kidney Beans', 'Nutmeg', 'Milk'}),
       frozenset({'Eggs', 'Onion', 'Yogurt', 'Nutmeg', 'Milk'}),
       frozenset({'Eggs', 'Nutmeg', 'Yogurt', 'Kidney Beans', 'Milk'}),
       frozenset({'Nutmeg', 'Onion', 'Yogurt', 'Kidney Beans', 'Milk'})],
      dtype=object)